### ISSUE TITLE
Android build error with latest compileSdkVersion version

### ISSUE THREAD

**Issue by userlab-alejandravelasquez** [VittoriDavide/react-native-barcode-creator#10]
Hi, i have an error with my compileSdkVersion version 33

What went wrong:
Could not determine the dependencies of task ':react-native-barcode-creator:bundleLibCompileToJarDebug'.
> Could not create task ':react-native-barcode-creator:compileDebugJavaWithJavac'.
   > In order to compile Java 9+ source, please set compileSdkVersion to 30 or above

the version in the build.gradle needs to be updated to 33, it is now at 29

**Comment by AnthonyMwangi** [comment]
Getting the same issue
```
"react": "18.2.0",
"react-native": "0.72.6",
"react-native-barcode-creator": "^0.1.5",
```

**Comment by Youngermaster** [comment]
I'm getting the same issue:
```json
{
...
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-barcode-creator": "^0.1.5",
...
}
```

**Comment by Youngermaster** [comment]
@userlab-alejandravelasquez @Alserk Hey, I solved it by manually updating the compile version needed for my project at `node_modules/react-native-barcode-creator/android/build.gradle`:
<img width="797" alt="image" src="https://github.com/VittoriDavide/react-native-barcode-creator/assets/36933318/5e15454c-9d7c-4e50-970e-ab28eb72720a">


@VittoriDavide If you could update the `android/build.gradle` to newer versions it would be great!

**Comment by Dat-Mobile** [comment]
> @userlab-alejandravelasquez @Alserk Hey, I solved it by manually updating the compile version needed for my project at `node_modules/react-native-barcode-creator/android/build.gradle`: <img alt="image" width="797" src="https://private-user-images.githubusercontent.com/36933318/291669782-5e15454c-9d7c-4e50-970e-ab28eb72720a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTIzMDEsIm5iZiI6MTcwMzE1MjAwMSwicGF0aCI6Ii8zNjkzMzMxOC8yOTE2Njk3ODItNWUxNTQ1NGMtOWQ3Yy00ZTUwLTk3MGUtYWIyOGViNzI3MjBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA5NDY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMjA5OTdlNWJlZTY1ZGZkMDNjMjE2M2VjYmY2YjYyZmFmMmE5YTdmZTI3NGMyZDQzODk1ZGJkNTFjOWE2MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CDBb77QUr_D5vxdTl0TuVHT8knk8f4X_5fLXkAomF7k">
> 
> @VittoriDavide If you could update the `android/build.gradle` to newer versions it would be great!

This works for me, please merge this ASAP !!

**Comment by Youngermaster** [comment]
> This works for me, please merge this ASAP !!

@Dat-Mobile Glad it helped you, and yeah I hope the owner can merge the #13 Pull Request. But for now that's a workaround for most people 👍🏻

**Comment by Dat-Mobile** [comment]
Really good work @Youngermaster , for now might only patch-package help
