### ISSUE TITLE
React Native v0.71.14

### ISSUE THREAD

**Issue by Gambitboy** [VittoriDavide/react-native-barcode-creator#11]
Getting an android build issue after upgrading my app to 0.71.14

Looks like the auto linking is failing, I think.

`react-native-barcode-creator:verifyReleaseResources FAILED`

```
ERROR: .../node_modules/react-native-barcode-creator/android/build/intermediates/merged_res/release/values/values.xml:2717: AAPT: error: resource android:attr/lStar not found.
```

**Comment by hienhodeveloper** [comment]
Same issue when build release
