### ISSUE TITLE
_reactNative.NativeModules.BarcodeCreatorViewManager.getConstants

### ISSUE THREAD

**Issue by rinaldycodes** [VittoriDavide/react-native-barcode-creator#7]
null is not an object (evaluating '_reactNative.NativeModules.BarcodeCreatorViewManager.getConstants')

**Comment by rinaldycodes** [comment]
> what constants are you trying to use ? If you use as in the Readme example is not working for you ?

im using expo, got that error

**Comment by VittoriDavide** [comment]
When I created the library, it was not possible to add Native Code to Expo. Now I am seeing that they are allowing this https://docs.expo.dev/modules/existing-library/, but it requires some extension on the current code

**Comment by Munir-Hassan** [comment]
> When I created the library, it was not possible to add Native Code to Expo. Now I am seeing that they are allowing this https://docs.expo.dev/modules/existing-library/, but it requires some extension on the current code

what is the solution for this? I am using expo too. expo sdk 48. How do I run it in expo? Please help

**Comment by lennertcl** [comment]
Any updates on this? Can we use this with expo?

**Comment by hrqmonteiro** [comment]
Same thing here. Unusable.

![image](https://github.com/VittoriDavide/react-native-barcode-creator/assets/17055027/028d4786-da7b-4f83-acbb-ab938891c04f)

**Comment by VittoriDavide** [comment]
To run it on expo it should be enough to make a prebuild and use a development build
