### ISSUE TITLE
react-native-barcode-creator:verifyReleaseResources

### ISSUE THREAD

**Issue by ManojMomo** [VittoriDavide/react-native-barcode-creator#8]
Is there any option to resolve this issue?

**Comment by VittoriDavide** [comment]
Can you elaborate more on this issue pls

**Comment by Mlg29** [comment]
@VittoriDavide  the error occur when trying to build the app. i did ./gradlew assembleRelease and i get ( Task :react-native-barcode-creator:verifyReleaseResources FAILED )
