### ISSUE TITLE
Error Build

### ISSUE THREAD

**Issue by yossularko** [VittoriDavide/react-native-barcode-creator#9]
I am getting error while building apk for android. This is the error message:

`*What went wrong:
Execution failed for task ':react-native-barcode-creator:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:D:\ReactNative\IndotoolStore\node_modules\react-native-barcode-creator\android\build\intermediates\merged_res\release\values\values.xml:2717: AAPT: error: resource android:attr/lStar not found.`

and this is my installed dependencies: 
"dependencies": {
    "@notifee/react-native": "^7.4.0",
    "@react-native-async-storage/async-storage": "^1.17.11",
    "@react-native-clipboard/clipboard": "^1.11.1",
    "@react-native-community/netinfo": "^9.3.7",
    "@react-navigation/bottom-tabs": "^6.5.3",
    "@react-navigation/native": "^6.1.2",
    "@react-navigation/native-stack": "^6.9.8",
    "@tanstack/react-query": "^4.24.4",
    "axios": "^0.27.2",
    "crypto-js": "^3.3.0",
    "react": "18.2.0",
    "react-hook-form": "^7.43.1",
    "react-native": "0.71.2",
    "react-native-barcode-creator": "^0.1.5",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.19.0",
    "react-native-svg": "^13.7.0",
    "react-native-vector-icons": "^9.2.0"
  }

**Comment by Hassam34** [comment]
I have same error

**Comment by VittoriDavide** [comment]
should be fine now
